SaoBei/Controllers/AdversariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SaoBei.Models;
using SaoBei.Negocio;

namespace SaoBei.Controllers
{
    [Authorize(Roles = "Diretoria")]
    public class AdversariosController : Controller
    {
        // GET: Adversario
        public ActionResult Index(string sortOrder, string filtroAtual,
                                    string filtro, int? page,
                                    string ativoFiltro,
                                    string ativoFiltroAtual)
        {
            try
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.NomeSort = string.IsNullOrEmpty(sortOrder) ? "nome_desc" : "";

                if (filtro != null)
                {
                    page = 1;
                }
                else
                {
                    filtro = filtroAtual;
                }

                if (ativoFiltro != null)
                {
                    page = 1;
                }
                else
                {
                    ativoFiltro = ativoFiltroAtual;
                }

                ViewBag.FiltroAtual = filtro;

                AdversarioBll adversarioBll = new AdversarioBll();

                return View("~/Views/Adversarios/Index.cshtml", adversarioBll.BuscarAdversarios(page, filtro, sortOrder, ativoFiltro, 10));
            }
            catch (Exception exception)
            {
                LogBll.GravarErro(exception, User.Identity.Name);
                return View("~/Views/Adversarios/Index.cshtml").ComMensagem(Resources.Geral.ContateAdministrador, TipoMensagem.Erro);
            }
        }

        //GET
        public ActionResult Adversario(int? id)
        {
            try
            {
                Adversario adversario;

                if (id == null)
                {
                    adversario = new Adversario();
                }
                else
                {
                    adversario = AdversarioBll.RetornarAdversario(id);
                }

                return View(adversario);
            }
            catch (Exception exception)
            {
                LogBll.GravarErro(exception, User.Identity.Name);
                return RedirectToAction("Index").ComMensagem(Resources.Geral.ContateAdministrador, TipoMensagem.Erro);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adversario([Bind(Include = "ID,Nome,NomeContato,Telefone,Ativo")] Adversario adversario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AdversarioBll adversarioBll = new AdversarioBll();

                    if (adversario.ID > 0)
                    {
                        adversarioBll.Atualizar(adversario);
                        LogBll.GravarInformacao(string.Format(Resources.Adversario.AtualizacaoLog, adversario.ID), "", User.Identity.Name);
                        return RedirectToAction("Index").ComMensagem(Resources.Adversario.AdversarioSalvo, TipoMensagem.Sucesso);
                    }
                    else
                    {
                        adversarioBll.Criar(adversario);
                        LogBll.GravarInformacao(string.Format(Resources.Calendario.CriacaoLog, adversario.ID), "", User.Identity.Name);
                        return RedirectToAction("Index").ComMensagem(Resources.Adversario.AdversarioSalvo, TipoMensagem.Sucesso);
                     
                    }
                }

                return View(adversario);
            }
            catch (Exception exception)
            {
                LogBll.GravarErro(exception, User.Identity.Name);
                return RedirectToAction("Index").ComMensagem(Resources.Geral.ContateAdministrador, TipoMensagem.Erro);
            }
        }
    }
}

SaoBei/Controllers/LocaisJogoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SaoBei.Models;
using SaoBei.Negocio;

namespace SaoBei.Controllers
{
    [Authorize(Roles = "Diretoria")]
    public class LocaisJogoController : Controller
    {
        // GET: LocaisJogo
        public ActionResult Index(string sortOrder, string filtroAtual,
                                    string filtro, int? page,
                                    string ativoFiltro,
                                    string ativoFiltroAtual)
        {
            try
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.NomeSort = string.IsNullOrEmpty(sortOrder) ? "nome_desc" : "";

                if (filtro != null)
                {
                    page = 1;
                }
                else
                {
                    filtro = filtroAtual;
                }

                if (ativoFiltro != null)
                {
                    page = 1;
                }
                else
                {
                    ativoFiltro = ativoFiltroAtual;
                }

                ViewBag.FiltroAtual = filtro;
                ViewBag.AtivoFiltroAtual = ativoFiltro;

                LocalJogoBll localJogoBll = new LocalJogoBll();

                return View("~/Views/LocaisJogo/Index.cshtml", localJogoBll.BuscarLocalJogos(page, filtro, sortOrder, ativoFiltro, 10));
            }
            catch (Exception exception)
            {
                LogBll.GravarErro(exception, User.Identity.Name);
                return View("~/Views/LocaisJogo/Index.cshtml").ComMensagem(Resources.Geral.ContateAdministrador, TipoMensagem.Erro);
            }
        }

        //GET
        public ActionResult LocalJogo(int? id)
        {
            try
            {
                LocalJogo localJogo;

                if (id == null)
                {
                    localJogo = new LocalJogo();
                }
                else
                {
                    localJogo = LocalJogoBll.RetornarLocalJogo(id);
                }

                return View(localJogo);
            }
            catch (Exception exception)
            {
                LogBll.GravarErro(exception, User.Identity.Name);
                return RedirectToAction("Index").ComMensagem(Resources.Geral.ContateAdministrador, TipoMensagem.Erro);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LocalJogo([Bind(Include = "ID,Nome,ValorJogo,Ativo")] LocalJogo localJogo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    LocalJogoBll localJogoBll = new LocalJogoBll();

                    if (localJogo.ID > 0)
                    {
                        localJogoBll.Atualizar(localJogo);
                        LogBll.GravarInformacao(string.Format(Resources.LocalJogo.AtualizacaoLog, localJogo.ID), "", User.Identity.Name);
                        return RedirectToAction("Index").ComMensagem(Resources.LocalJogo.LocalJogoSalvo, TipoMensagem.Sucesso);
                    }
                    else
                    {
                        localJogoBll.Criar(localJogo);
                        LogBll.GravarInformacao(string.Format(Resources.LocalJogo.CriacaoLog, localJogo.ID), "", User.Identity.Name);
                        return RedirectToAction("Index").ComMensagem(Resources.LocalJogo.LocalJogoSalvo, TipoMensagem.Sucesso);

                    }
                }

                return View(localJogo);
            }
            catch (Exception exception)
            {
                LogBll.GravarErro(exception, User.Identity.Name);
                return RedirectToAction("Index").ComMensagem(Resources.Geral.ContateAdministrador, TipoMensagem.Erro);
            }
        }

        public ActionResult Detalhes(int? id)
        {
            try
            {
                LocalJogo localJogo = LocalJogoBll.RetornarLocalJogo(id);

                return View(localJogo);
            }
            catch (Exception exception)
            {
                LogBll.GravarErro(exception, User.Identity.Name);
                return RedirectToAction("Index").ComMensagem(Resources.Geral.ContateAdministrador, TipoMensagem.Erro);
            }
        }
    }
}

SaoBei/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - São Beiçado</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/all.css")
    @Styles.Render("~/Content/bootstrap-datepicker3.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/Chart.js")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>                
                <a href="#" onclick="location.href='@Url.Action("Index", "Home")'">
                    <img src="~/Imagens/logo.jpg" class="logo" />
                </a>
            </div>            
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Administração <span class="caret"></span>
                        </a>
                        <ul id="menu-admin" class="dropdown-menu">
                            <li>@Html.ActionLink("Integrantes", "Index", "Integrantes")</li>
                            <li>@Html.ActionLink("Calendários", "Index", "Calendarios")</li>
                            <li>@Html.ActionLink("Mensalidades", "Index", "Mensalidades")</li>
                        </ul>
                    </li>                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Futebol <span class="caret"></span>
                        </a>
                        <ul id="menu-admin" class="dropdown-menu">
                            <li>@Html.ActionLink("Adversários", "Index", "Adversarios")</li>
                            <li>@Html.ActionLink("Jogos", "Index", "Jogos")</li>
                            <li>@Html.ActionLink("Locais de jogo", "Index", "LocaisJogo")</li>
                        </ul>
                    </li>                    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            @Context.User.Identity.Name
                            <span class="caret"></span>
                            <ul class="dropdown-menu">
                                <li>
                                    @Html.ActionLink("Sair", "LogOff", "Autenticacao")
                                </li>
                            </ul>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @{Html.RenderPartial("_Mensagem");}
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - São Beiçado</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/jquery.mask.js")
    @Scripts.Render("~/Scripts/jquery.maskMoney.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datepicker.min.js")    
    @Scripts.Render("~/Scripts/Views/Geral.js")
    @Scripts.Render("~/Scripts/bootbox.js")
    @RenderSection("scripts", required: false)
</body>
</html>

SaoBei/Views/Shared/_Mensagem.cshtml
@Scripts.Render("~/bundles/jquery")
@if (TempData["Mensagem"] != null)
{
    <br />
    <div class="box-msg-erro">
        <div id="mensagem" class="alert @Html.Raw(TempData["ClasseAlert"].ToString())">
            <b>@TempData["Mensagem"]</b>
            <button type="button" class="close" data-dismiss="alert">×</button>
        </div>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {

        if ($('#mensagem').is('[class*="alert-"]'))
        {
            setTimeout(function () {
                $('#mensagem').slideUp(1000);
            }, 10000);
        }
    })
</script>