SaoBei/Models/Calendario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SaoBei.Models
{
    public class Calendario
    {
        public Calendario()
        {
            Ano = DateTime.Now.Year;
            DataVencimentoAnuidade = DateTime.Now.Date;
            Marco = true;
            Abril = true;
            Maio = true;
            Junho = true;
            Julho = true;
            Agosto = true;
            Setembro = true;
            Outubro = true;
            Novembro = true;
            Dezembro = true;
        }

        public int ID { get; set; }

        [Required]
        public int Ano { get; set; }

        [Display(Name = "Data de vencimento da anuidade")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DataVencimentoAnuidade { get; set; }

        public bool Janeiro { get; set; }

        public bool Fevereiro { get; set; }

        [Display(Name="Março")]
        public bool Marco { get; set; }

        public bool Abril { get; set; }

        public bool Maio { get; set; }

        public bool Junho { get; set; }

        public bool Julho { get; set; }

        public bool Agosto { get; set; }

        public bool Setembro { get; set; }

        public bool Outubro { get; set; }

        public bool Novembro { get; set; }

        public bool Dezembro { get; set; }

        [Display(Name="Valor mensalidade")]
        public decimal ValorMensalidade { get; set; }

        [Display(Name = "Valor anuidade")]
        public decimal ValorAnuidade { get; set; }
    }
}

SaoBei/Controllers/CalendariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SaoBei.Models;
using SaoBei.Negocio;

namespace SaoBei.Controllers
{
    [Authorize(Roles="Diretoria")]
    public class CalendariosController : Controller
    {
        private Contexto db = new Contexto();

        // GET: Calendarios
        public ActionResult Index()
        {
            try
            {
                IQueryable<Calendario> calendarios = CalendarioBll.ListarCalendarios();

                return View(calendarios);
            }
            catch (Exception exception)
            {
                LogBll.GravarErro(exception, User.Identity.Name);
                return RedirectToAction("Index").ComMensagem(Resources.Geral.ContateAdministrador, TipoMensagem.Erro);
            }
        }

        // GET
        public ActionResult Calendario(int? id)
        {
            try
            {
                Calendario calendario;


                if (id == null)
                {
                    calendario = new Calendario();
                }
                else
                {
                    calendario = CalendarioBll.RetornarCalendario(id);
                }

                return View(calendario);
            }
            catch (Exception exception)
            {
                LogBll.GravarErro(exception, User.Identity.Name);
                return RedirectToAction("Index").ComMensagem(Resources.Geral.ContateAdministrador, TipoMensagem.Erro);
            }
        }

        // POST: Calendarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Calendario([Bind(Include = "ID,Ano,Janeiro,Fevereiro,Marco,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro,ValorMensalidade,ValorAnuidade,DataVencimentoAnuidade")] Calendario calendario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CalendarioBll calendarioBll = new CalendarioBll();                    

                    if (calendario.ID > 0)
                    {
                        if (CalendarioBll.VericarCalendarioExistente(calendario, TipoOperacao.Update))
                        {
                            return View().ComMensagem(string.Format(Resources.Calendario.CalendarioExistente, calendario.Ano), TipoMensagem.Aviso);
                        }
                        else
                        {
                            calendarioBll.Atualizar(calendario);

                            MensalidadeIntegranteBll mensalidadeIntegranteBll = new MensalidadeIntegranteBll();
                            mensalidadeIntegranteBll.CriarMensalidadesTodosIntegrantesCalendario(calendario);

                            LogBll.GravarInformacao(string.Format(Resources.Calendario.AtualizacaoLog, calendario.ID), "", User.Identity.Name);
                            return RedirectToAction("Index").ComMensagem(Resources.Calendario.CalendarioAtualizado, TipoMensagem.Sucesso);
                        }
                    }
                    else
                    {
                        if (CalendarioBll.VericarCalendarioExistente(calendario, TipoOperacao.Create))
                        {
                            return View().ComMensagem(string.Format(Resources.Calendario.CalendarioExistente, calendario.Ano), TipoMensagem.Aviso);
                        }
                        else
                        {
                            calendarioBll.Criar(calendario);

                            MensalidadeIntegranteBll mensalidadeIntegranteBll = new MensalidadeIntegranteBll();
                            mensalidadeIntegranteBll.CriarMensalidadesTodosIntegrantesCalendario(calendario);

                            LogBll.GravarInformacao(string.Format(Resources.Calendario.CriacaoLog, calendario.ID), "", User.Identity.Name);
                            return RedirectToAction("Index").ComMensagem(Resources.Calendario.CalendarioSalvo, TipoMensagem.Sucesso);
                        }
                    }
                }

                return View(calendario);
            }
            catch (Exception exception)
            {
                LogBll.GravarErro(exception, User.Identity.Name);
                return RedirectToAction("Index").ComMensagem(Resources.Geral.ContateAdministrador, TipoMensagem.Erro);
            }
        }

        public ActionResult Detalhes(int? id)
        {
            try
            {
                Calendario calendario = CalendarioBll.RetornarCalendario(id);
                return View(calendario);
            }
            catch (Exception exception)
            {
                LogBll.GravarErro(exception, User.Identity.Name);
                return RedirectToAction("Index").ComMensagem(Resources.Geral.ContateAdministrador, TipoMensagem.Erro);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SaoBei/Views/Calendarios/Calendario.cshtml
@model SaoBei.Models.Calendario

@{
    ViewBag.Title = "Calendário";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Calendário</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="row">            
        <div class="col-md-4">
            @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="panel panel-default">
        <div class="panel-heading">Meses</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Janeiro)
                        @Html.LabelFor(model => model.Janeiro, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Janeiro, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Fevereiro)
                        @Html.LabelFor(model => model.Fevereiro, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Fevereiro, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Marco)
                        @Html.LabelFor(model => model.Marco, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Marco, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Abril)
                        @Html.LabelFor(model => model.Abril, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Abril, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Maio)
                        @Html.LabelFor(model => model.Maio, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Maio, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Junho)
                        @Html.LabelFor(model => model.Junho, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Junho, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Julho)
                        @Html.LabelFor(model => model.Julho, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Julho, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Agosto)
                        @Html.LabelFor(model => model.Agosto, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Agosto, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Setembro)
                        @Html.LabelFor(model => model.Setembro, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Setembro, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Outubro)
                        @Html.LabelFor(model => model.Outubro, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Outubro, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Novembro)
                        @Html.LabelFor(model => model.Novembro, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Novembro, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Dezembro)
                        @Html.LabelFor(model => model.Dezembro, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Dezembro, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>        

    <div class="row">            
        <div class="col-md-4">
            @Html.LabelFor(model => model.ValorMensalidade, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.ValorMensalidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ValorMensalidade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">            
        <div class="col-md-4">
            @Html.LabelFor(model => model.ValorAnuidade, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.ValorAnuidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ValorAnuidade, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.DataVencimentoAnuidade, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.DataVencimentoAnuidade, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.DataVencimentoAnuidade, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-10">
            <button type="submit" class="btn btn-primary" title="Salvar"><i class="glyphicon glyphicon-floppy-save"></i> Salvar</button>
            <button type="button" class="btn btn-danger" title="Voltar" onclick="location.href='@Url.Action("Index", "Calendarios")'"><i class="glyphicon glyphicon-arrow-left"></i> Voltar</button>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/Views/Calendarios/Calendario.js")
}

SaoBei/Views/Calendarios/Details.cshtml
@model SaoBei.Models.Calendario

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Usuário</h4>
        </div>
        <div class="modal-body">
            <p>@Html.DisplayNameFor(model => model.Ano): @Html.DisplayFor(model => model.Ano)</p>
            <p>@Html.DisplayNameFor(model => model.Janeiro): @Html.DisplayFor(model => model.Janeiro)</p>
            <p>@Html.DisplayNameFor(model => model.Fevereiro): @Html.DisplayFor(model => model.Fevereiro)</p>
            <p>@Html.DisplayNameFor(model => model.Marco): @Html.DisplayFor(model => model.Marco)</p>
            <p>@Html.DisplayNameFor(model => model.Abril): @Html.DisplayFor(model => model.Abril)</p>
            <p>@Html.DisplayNameFor(model => model.Marco): @Html.DisplayFor(model => model.Marco)</p>
            <p>@Html.DisplayNameFor(model => model.Maio): @Html.DisplayFor(model => model.Maio)</p>
            <p>@Html.DisplayNameFor(model => model.Junho): @Html.DisplayFor(model => model.Junho)</p>
            <p>@Html.DisplayNameFor(model => model.Julho): @Html.DisplayFor(model => model.Julho)</p>
            <p>@Html.DisplayNameFor(model => model.Agosto): @Html.DisplayFor(model => model.Agosto)</p>
            <p>@Html.DisplayNameFor(model => model.Setembro): @Html.DisplayFor(model => model.Setembro)</p>
            <p>@Html.DisplayNameFor(model => model.Outubro): @Html.DisplayFor(model => model.Outubro)</p>
            <p>@Html.DisplayNameFor(model => model.Novembro): @Html.DisplayFor(model => model.Novembro)</p>
            <p>@Html.DisplayNameFor(model => model.Dezembro): @Html.DisplayFor(model => model.Dezembro)</p>
            <p>@Html.DisplayNameFor(model => model.ValorMensalidade): @Html.DisplayFor(model => model.ValorMensalidade)</p>
            <p>@Html.DisplayNameFor(model => model.ValorAnuidade): @Html.DisplayFor(model => model.ValorAnuidade)</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
    </div>
</div>

SaoBei/Views/Calendarios/Detalhes.cshtml
@model SaoBei.Models.Calendario

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Usuário</h4>
        </div>
        <div class="modal-body">
            <p>@Html.DisplayNameFor(model => model.Ano): @Html.DisplayFor(model => model.Ano)</p>
            <p>@Html.DisplayNameFor(model => model.Janeiro): @Html.DisplayFor(model => model.Janeiro)</p>
            <p>@Html.DisplayNameFor(model => model.Fevereiro): @Html.DisplayFor(model => model.Fevereiro)</p>
            <p>@Html.DisplayNameFor(model => model.Marco): @Html.DisplayFor(model => model.Marco)</p>
            <p>@Html.DisplayNameFor(model => model.Abril): @Html.DisplayFor(model => model.Abril)</p>
            <p>@Html.DisplayNameFor(model => model.Marco): @Html.DisplayFor(model => model.Marco)</p>
            <p>@Html.DisplayNameFor(model => model.Maio): @Html.DisplayFor(model => model.Maio)</p>
            <p>@Html.DisplayNameFor(model => model.Junho): @Html.DisplayFor(model => model.Junho)</p>
            <p>@Html.DisplayNameFor(model => model.Julho): @Html.DisplayFor(model => model.Julho)</p>
            <p>@Html.DisplayNameFor(model => model.Agosto): @Html.DisplayFor(model => model.Agosto)</p>
            <p>@Html.DisplayNameFor(model => model.Setembro): @Html.DisplayFor(model => model.Setembro)</p>
            <p>@Html.DisplayNameFor(model => model.Outubro): @Html.DisplayFor(model => model.Outubro)</p>
            <p>@Html.DisplayNameFor(model => model.Novembro): @Html.DisplayFor(model => model.Novembro)</p>
            <p>@Html.DisplayNameFor(model => model.Dezembro): @Html.DisplayFor(model => model.Dezembro)</p>
            <p>@Html.DisplayNameFor(model => model.ValorMensalidade): @Html.DisplayFor(model => model.ValorMensalidade)</p>
            <p>@Html.DisplayNameFor(model => model.ValorAnuidade): @Html.DisplayFor(model => model.ValorAnuidade)</p>
            <p>@Html.DisplayNameFor(model => model.DataVencimentoAnuidade): @Html.DisplayFor(model => model.DataVencimentoAnuidade)</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
    </div>
</div>

SaoBei/Views/Calendarios/Index.cshtml
@model IEnumerable<SaoBei.Models.Calendario>

@{
    ViewBag.Title = "Calendários";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Calendários</h2>

<div class="form-group">
    <button type="button" title="Novo" name="btnNovo" id="btnNovo" class="btn btn-success" onclick="location.href='@Url.Action("Calendario", "Calendarios")'">
        <i class="glyphicon glyphicon-plus"></i> Novo calendário
    </button>
</div>
<div class="table-responsive">
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ano)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorMensalidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorAnuidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataVencimentoAnuidade)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ano)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorMensalidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorAnuidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataVencimentoAnuidade)
                </td>
                <td>
                    <div class="pull-right">
                        <button type="button" class="btn btn-primary edit" title="Editar" onclick="location.href='@Url.Action("Calendario", "Calendarios", new { item.ID })'"><i class="glyphicon glyphicon-edit"></i></button>
                        <button class="btn btn-default details" title="Visualizar" data-id="@item.ID"><i class="glyphicon glyphicon-new-window"></i></button>
                    </div>
                </td>
            </tr>
        }
    </table>
</div>
<div id="detalhes" class="modal"></div>

@section Scripts {
    @Scripts.Render("~/Scripts/Views/Calendarios/Index.js")
}